### ISSUE TITLE
Can we get the --clean/-x option described in the options list?

### ISSUE THREAD

**Issue by skydivedan** [erica/remind#2]
This is a great, simple utility. Just had one question.
Can we show `--clean` and `-x` along with the other options. Very not a big deal (I just looked it up in the source). But thought I'd mention it.

**Comment by erica** [comment]
I felt it too big a hammer for casual use although extremely useful for debugging. I decided not to eliminate it entirely so that discussions (entirely like this) could happen.

See if you can find the other hidden features. :)
